# Generated by Django 4.0.5 on 2022-06-16 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_mymodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymodel',
            name='age',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
